version: "3"
name: "traveller-db"
services:
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./scripts/:/code
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
